// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTZfCw4xe-7tTihpuC896Q1phowd0HGdI',
    appId: '1:5202461809:web:e298021047f4bd785947d0',
    messagingSenderId: '5202461809',
    projectId: 'fittrack-eea87',
    authDomain: 'fittrack-eea87.firebaseapp.com',
    storageBucket: 'fittrack-eea87.firebasestorage.app',
    measurementId: 'G-0X6P5XQ362',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgz5-aIJ19bYa3wpeUBbec_H5m57RUAI8',
    appId: '1:5202461809:android:d8a6377dd50811bc5947d0',
    messagingSenderId: '5202461809',
    projectId: 'fittrack-eea87',
    storageBucket: 'fittrack-eea87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKrRdP9CzW4Dc2KlfcRrqQ0AuFmdYQ3Y',
    appId: '1:5202461809:ios:010a18bdff781e855947d0',
    messagingSenderId: '5202461809',
    projectId: 'fittrack-eea87',
    storageBucket: 'fittrack-eea87.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoKrRdP9CzW4Dc2KlfcRrqQ0AuFmdYQ3Y',
    appId: '1:5202461809:ios:010a18bdff781e855947d0',
    messagingSenderId: '5202461809',
    projectId: 'fittrack-eea87',
    storageBucket: 'fittrack-eea87.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTZfCw4xe-7tTihpuC896Q1phowd0HGdI',
    appId: '1:5202461809:web:84739c243f56e8e55947d0',
    messagingSenderId: '5202461809',
    projectId: 'fittrack-eea87',
    authDomain: 'fittrack-eea87.firebaseapp.com',
    storageBucket: 'fittrack-eea87.firebasestorage.app',
    measurementId: 'G-88XMPP75P8',
  );
}
